#-----------------------------------------
# Continuous integration with Travis CI
# http://docs.travis-ci.com/
#	
# Configuration file
#-----------------------------------------

sudo: required
dist: trusty
os: linux

branches: 
  only: 
    - master

# overwriting default 'Ruby' by 'C' environment
# which does not affect Red language script execution
language: c

before_install:
  - sudo dpkg --add-architecture i386
  - sudo apt-get update

install: 
  - sudo apt-get install -y libc6:i386 libcurl3:i386
  - sudo chmod +x red-063-linux

script: ./red-063-linux -s run-all-tests.red

